spring:
  h2:
    console:
      enabled: true
  datasource:
    url:  jdbc:h2:tcp://localhost/~/smtc
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    show-sql: true
#  profiles:
#    include:
#      - oauth


#logging:
#  level:
#    org.hibernate: trace


